title: Diving into Azure
description:
  Take a deep dive into a selection of all the awesome things Azure has to offer. All
  mixed up with .Net Core, React, TypeScript and some private projects.

url: https://johanohlin.github.io
baseurl: ""
paginate_path: "blog/page:num/"
permalink: blog/:title/

markdown: kramdown
highlighter: rouge
plugins: [jekyll-paginate]
paginate: 5

# Disqus Comments
comments: true
disqus:
  # Leave shortname blank to disable comments site-wide.
  # Disable comments for any post by adding `comments: false` to that post's YAML Front Matter.
  shortname: diving-into-azure.disqus.com

navigation:
  - title: Home
    url: /index.html
  - title: About
    url: /about
  - title: Contact
    url: /contact

social:
  github: johanohlin
  twitter: ohlinjohan
  email: johan.ohlin@outlook.com

google_analytics: "UA-58263416-1"

# Exclude these files from your production _site
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CNAME
